# Site settings
title: Freedom To Go
tagline: It’s our future. How will we go?
description: > # ignore newlines
  Description
# email: 

baseurl: ""
url: ""
# paginate: 10
# paginate_path: "posts/:num"

# Build settings
markdown: kramdown
permalink: pretty
