# Site settings
title: Kevin McCarthy
tagline: IT &amp; Web Development

email: kevin@kaymic.com
description: "Experienced Web Developer with extensive knowledge in essentially all aspects of Internet Services, Information Technology, and Digital Multimedia."
baseurl: ""
url: "http://kaymic.com"
twitter_username: kjmagic13
github_username:  kjmagic13
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty
